"""Core utilities and shared infrastructure."""

from .constants import (
    ModeType,
    BINARY_THRESHOLD_GT,
    BINARY_THRESHOLD_GEN,
    BINARY_THRESHOLD,
    MAX_WHITE_PERCENTAGE,
    DEFAULT_GRADIENT_CLIP_NORM,
    DEFAULT_EMA_UPDATE_AFTER_STEP,
    DEFAULT_EMA_UPDATE_EVERY,
    DEFAULT_MIN_SNR_GAMMA,
    DEFAULT_PERCEPTUAL_WEIGHT,
    DEFAULT_CHANNELS,
    DEFAULT_ATTENTION_LEVELS,
    DEFAULT_NUM_RES_BLOCKS,
    DEFAULT_NUM_HEAD_CHANNELS,
    DEFAULT_NUM_WORKERS,
    DEFAULT_DUAL_IMAGE_KEYS,
)
from .cuda_utils import setup_cuda_optimizations

__all__ = [
    # Enums
    'ModeType',
    # Constants
    'BINARY_THRESHOLD_GT',
    'BINARY_THRESHOLD_GEN',
    'BINARY_THRESHOLD',
    'MAX_WHITE_PERCENTAGE',
    'DEFAULT_GRADIENT_CLIP_NORM',
    'DEFAULT_EMA_UPDATE_AFTER_STEP',
    'DEFAULT_EMA_UPDATE_EVERY',
    'DEFAULT_MIN_SNR_GAMMA',
    'DEFAULT_PERCEPTUAL_WEIGHT',
    'DEFAULT_CHANNELS',
    'DEFAULT_ATTENTION_LEVELS',
    'DEFAULT_NUM_RES_BLOCKS',
    'DEFAULT_NUM_HEAD_CHANNELS',
    'DEFAULT_NUM_WORKERS',
    'DEFAULT_DUAL_IMAGE_KEYS',
    # Utilities
    'setup_cuda_optimizations',
]
